services:
  # MySql DB
  app-db:
    restart: always
    image: mysql:8
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - ${EXPORT_PORT_DB}:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_sql:/docker-entrypoint-initdb.d

  #MySql Web UI
  php-my-admin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
      - ${EXPORT_PORT_PHPMYADMIN}:80 #Forwars the exposed port 80 on the container to port 8081 on the host machine
    environment:        
      PMA_HOST: app-db

  # Website
  app-service:
    container_name: app-service
    restart: always
    build:
      context: .
      dockerfile: ./service/Dockerfile
    ports:
      - ${EXPORT_PORT_SERVICE}:8080
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASSWD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - app-db
